
vim.pack.add({ 'https://github.com/ibhagwan/fzf-lua' })
vim.pack.add({ 'https://github.com/leblocks/toggle.nvim' })
vim.pack.add({ 'https://github.com/miikanissi/modus-themes.nvim' })
vim.pack.add({ 'https://github.com/neovim/nvim-lspconfig' })
vim.pack.add({ 'https://github.com/nvim-lualine/lualine.nvim' })
vim.pack.add({ 'https://github.com/tpope/vim-commentary' })
vim.pack.add({ 'https://github.com/tpope/vim-fugitive' })
vim.pack.add({ 'https://github.com/tpope/vim-surround' })
vim.pack.add({ 'https://github.com/tpope/vim-unimpaired' })
vim.pack.add({ 'https://github.com/tpope/vim-vinegar' })
