properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installPowerToys
      directives:
        description: Install PowerToys
        allowPrerelease: true
      settings:
        id: Microsoft.PowerToys
        source: winget

    - resource: Microsoft.PowerToys.Configure/PowerToysConfigure
      dependsOn:
        - installPowerToys
      directives:
        description: Configure PowerToys
      settings:
        GeneralSettings:
          Startup: true
          AutoDownloadUpdates: true
          Theme: system
        Awake:
          Enabled: true
          KeepDisplayOn: true
          Mode: INDEFINITE
        FindMyMouse:
          Enabled: false
        PowerLauncher:
          Enabled: true
          ClearInputOnLaunch: true
          Theme: System
          TitleFontSize: 16
          GenerateThumbnailsFromFiles: false
          Plugins:
            - Name: "Calculator"
              Disabled: true
            - Name: "Folder"
              Disabled: true
            - Name: "History"
              Disabled: true
            - Name: "Windows Search"
              Disabled: true
            - Name: "OneNote"
              Disabled: true
            - Name: "PowerToys"
              Disabled: false
              IsGlobal: true
            - Name: "Program"
              Disabled: false
              IsGlobal: true
            - Name: "Registry Plugin"
              Disabled: true
            - Name: "Service"
              Disabled: true
            - Name: "Shell"
              Disabled: true
            - Name: "Windows System Commands"
              Disabled: false
              IsGlobal: true
            - Name: "Time and Date"
              Disabled: true
            - Name: "Unit Converter"
              Disabled: true
            - Name: "URI Handler"
              Disabled: true
            - Name: "Value Generator"
              Disabled: true
            - Name: "Visual Studio Code Workspaces"
              Disabled: true
            - Name: "Web Search"
              Disabled: true
            - Name: "Windows settings"
              IsGlobal: true
              Disabled: false
            - Name: "Windows Terminal"
              Disabled: true
            - Name: "Window Walker"
              Disabled: true

  configurationVersion: 0.2.0
