set -g cursor-blink off
set -g cursor-style block
set -g automatic-rename off

unbind-key C-v
set -g paste-detection off

# ===========================================
# Plugins
# ===========================================
set -g @plugin 'psmux-plugins/ppm'
set -g @plugin 'psmux-plugins/psmux-sensible'
set -g @plugin 'psmux-plugins/psmux-pain-control'
set -g @plugin 'psmux-plugins/psmux-theme-gruvbox'

set -g @gruvbox-variant 'dark'           # dark|light
set -g @gruvbox-contrast 'medium'        # soft|medium|hard
set -g @gruvbox-show-powerline 'on'
set -g @gruvbox-separator 'arrow'        # arrow|rounded|slant
set -g @gruvbox-show-icons 'on'
set -g @gruvbox-show-user 'on'
set -g @gruvbox-show-zoom 'on'           # zoom indicator
set -g @gruvbox-show-sync 'on'           # sync indicator
set -g @gruvbox-show-pane-count 'on'     # pane count badge

run-shell '~/.psmux/plugins/psmux-plugins/psmux-theme-gruvbox/psmux-theme-gruvbox.ps1'

# Initialize PPM (keep at the very bottom)
run '~/.psmux/plugins/psmux-plugins/ppm/ppm.ps1'

