
set -g cursor-blink off
set -g cursor-style block
set -g automatic-rename off

source-file '~/.psmux/plugins/psmux-plugins/psmux-sensible/plugin.conf'
source-file '~/.psmux/plugins/psmux-plugins/psmux-pain-control/plugin.conf'
source-file '~/.psmux/plugins/psmux-plugins/psmux-theme-gruvbox/plugin.conf'

